### ISSUE TITLE
Contribute to Hyper compose store

### ISSUE THREAD

**Issue by Gnep** [suda/hyper-tick#1]
Hi,

I'm one of the cofounders of Hyper.sh.

I just found this repo, and Thanks for writing this up. I'm working on a curation of Hyper-ready compose file: github.com/hyperhq/compose.hyper.sh. It will be GREAT to include your TICK stack into the collection. I'd LOVE to ask you to contribute.

Thanks!

**Comment by suda** [comment]
Hi Gnep! Sure thing! Added here: https://github.com/hyperhq/compose.hyper.sh/pull/1 :)
